texts_table = """\
CREATE TABLE IF NOT EXISTS texts (
    id          INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ON CONFLICT FAIL
                NOT NULL ON CONFLICT FAIL,
    filesname   TEXT UNIQUE ON CONFLICT FAIL NOT NULL ON CONFLICT FAIL,
    text_title  TEXT NOT NULL ON CONFLICT FAIL
)"""

sessions_table = """\
CREATE TABLE IF NOT EXISTS sessions (
    session_id  TEXT PRIMARY KEY AUTOINCREMENT UNIQUE ON CONFLICT FAIL
                NOT NULL ON CONFLICT FAIL,
    start_date  DATE NOT NULL ON CONFLICT FAIL,
    logged_in   BOOLEAN NOT NULL ON CONFLICT FAIL
    
)"""